### ISSUE TITLE
MySQL connection breaks after long period of idletime

### ISSUE THREAD

**Issue by Anthony-gamer** [C-Bouthoorn/Anthony-Server#9]
After a while MySQL connection breaks because of no queries made. (see error below)

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (/home/anthony/chatroom/node_modules/mysql/lib/protocol/Protocol.js:109:13)
    at Socket.<anonymous> (/home/anthony/chatroom/node_modules/mysql/lib/Connection.js:102:28)
    at emitNone (events.js:85:20)
    at Socket.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (node.js:383:13)
    at process._tickCallback (node.js:407:11)

npm ERR! Linux 3.19.0-56-generic
npm ERR! argv "/usr/local/bin/node-v5.9.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.9.1
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! anthonyserver@1.2.3 start: `nodejs server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the anthonyserver@1.2.3 start script 'nodejs server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the anthonyserver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nodejs server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs anthonyserver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls anthonyserver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/anthony/chatroom/npm-debug.log
```

**Comment by Anthony-gamer** [comment]
Hopefully fixed it with this commit: [server.coffee](https://github.com/C-Bouthoorn/Anthony-Server/commit/092ef1b9917cb515b059188c5e42456aca24270c)
